import { createClient } from "@supabase/supabase-js";
import { generateCopyAI } from "@/lib/copy-ai.server";
import { publishPaused } from "@/lib/meta/meta-ads.server";
const s:any = createClient(process.env.SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);
const WS="ab67e8e1-e147-48c9-bb68-a622d5f9c9fe", BRAND="2d46c624-c17a-419f-bf4b-5f0088e0b8fc";
const audience = { persona: "Adultos que frequentam o shopping, happy hour com amigos e família", idade: "21-55", localizacao: "Valinhos, Vinhedo, Louveira, Campinas", interesses: "chopp, cerveja, churrasco, happy hour, shopping", tipo: "frio" };
const { data: c, error } = await s.from("campaigns").insert({ workspace_id: WS, brand_id: BRAND, name: "TESTE – Vendas Chopp e Espeto Valinhos e região", objective: "sales", status: "approved", offer_product: "Chopp + espetinhos", offer_promise: "Happy hour com chopp gelado e espetinho na brasa na praça de alimentação", landing_url: "https://www.choppebreja.com.br", budget_daily: 20, audience, formats: ["static","video"] }).select().single();
if (error) throw error; console.log("campaign", c.id);
await s.from("creatives").update({ campaign_id: c.id, status: "approved" }).in("id", ["0414286d-df2d-4acd-93bb-dd597aaa07a3","4566efd0-bf1b-4db2-9185-440ebc82e5ef"]);
const brand = (await s.from("brands").select("*").eq("id", BRAND).single()).data;
const copy = await generateCopyAI(WS, "auto", brand, { campaign: c, objective: "vendas" }, 1);
console.log("copy engine", copy.engine, JSON.stringify(copy.content).slice(0,500));
await s.from("copies").insert({ workspace_id: WS, campaign_id: c.id, version: 1, status: "approved", content: copy.content });
const cr = (await s.from("creatives").select("id,title,preview_url,thumbnail_url").eq("campaign_id", c.id)).data;
const k = copy.content as any;
const r = await publishPaused({ name: c.name, objective: c.objective, dailyBudget: 20, landingUrl: `${c.landing_url}?utm_source=meta&utm_medium=paid&utm_campaign=teste`, primaryText: String(k.meta_ad ?? k.primary_text ?? c.offer_promise), headline: String(k.headline ?? k.headlines?.[0] ?? c.offer_product).slice(0,40), audience, creatives: cr.map((x:any)=>({id:x.id,title:x.title,url:x.preview_url,thumb:null})) });
console.log(JSON.stringify(r, null, 1));
await s.from("campaigns").update({ meta_campaign_id: r.campaignId, meta_adset_id: r.adsetId, meta_ad_ids: r.adIds, meta_delivery_status: "PAUSED" }).eq("id", c.id);
await s.from("publishing_jobs").insert({ workspace_id: WS, campaign_id: c.id, target: "meta", status: r.steps.some((x:any)=>x.status==="failed")?"partial":"done", mode: "live", log: r.steps.map((x:any)=>`${x.label}: ${x.detail}`).join("\n") });
