/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedInstagramRouteImport } from './routes/_authenticated/instagram'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedBrandsIndexRouteImport } from './routes/_authenticated/brands.index'
import { Route as AuthenticatedBrandsIdRouteImport } from './routes/_authenticated/brands.$id'
import { Route as AuthenticatedCampaignsIndexRouteImport } from './routes/_authenticated/campaigns.index'
import { Route as AuthenticatedCampaignsIdRouteImport } from './routes/_authenticated/campaigns.$id'
import { Route as AuthenticatedCampaignsNewRouteImport } from './routes/_authenticated/campaigns.new'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated/crm.index'
import { Route as AuthenticatedCrmCadencesRouteImport } from './routes/_authenticated/crm.cadences'
import { Route as AuthenticatedCrmDashboardRouteImport } from './routes/_authenticated/crm.dashboard'
import { Route as AuthenticatedCrmInboxRouteImport } from './routes/_authenticated/crm.inbox'
import { Route as AuthenticatedCrmIntegrationsRouteImport } from './routes/_authenticated/crm.integrations'
import { Route as AuthenticatedCrmSettingsRouteImport } from './routes/_authenticated/crm.settings'
import { Route as AuthenticatedCrmTasksRouteImport } from './routes/_authenticated/crm.tasks'
import { Route as AuthenticatedCrmLeadsIndexRouteImport } from './routes/_authenticated/crm.leads.index'
import { Route as AuthenticatedCrmLeadsIdRouteImport } from './routes/_authenticated/crm.leads.$id'
import { Route as ApiPublicCronAdsRouteImport } from './routes/api/public/cron/ads'
import { Route as ApiPublicCronCrmCadencesRouteImport } from './routes/api/public/cron/crm-cadences'
import { Route as ApiPublicCronCrmDailyRouteImport } from './routes/api/public/cron/crm-daily'
import { Route as ApiPublicCronInstagramRouteImport } from './routes/api/public/cron/instagram'
import { Route as ApiPublicMcpCallbackRouteImport } from './routes/api/public/mcp/callback'
import { Route as ApiPublicWebhooksWhatsappTokenRouteImport } from './routes/api/public/webhooks/whatsapp/$token'
import { Route as ApiPublicWebhooksMetaLeadgenTokenRouteImport } from './routes/api/public/webhooks/meta/leadgen/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstagramRoute = AuthenticatedInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrandsIndexRoute =
  AuthenticatedBrandsIndexRouteImport.update({
    id: '/brands/',
    path: '/brands/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBrandsIdRoute = AuthenticatedBrandsIdRouteImport.update({
  id: '/brands/$id',
  path: '/brands/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsIndexRoute =
  AuthenticatedCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignsIdRoute =
  AuthenticatedCampaignsIdRouteImport.update({
    id: '/campaigns/$id',
    path: '/campaigns/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignsNewRoute =
  AuthenticatedCampaignsNewRouteImport.update({
    id: '/campaigns/new',
    path: '/campaigns/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCrmCadencesRoute =
  AuthenticatedCrmCadencesRouteImport.update({
    id: '/cadences',
    path: '/cadences',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmDashboardRoute =
  AuthenticatedCrmDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmInboxRoute = AuthenticatedCrmInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCrmIntegrationsRoute =
  AuthenticatedCrmIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmSettingsRoute =
  AuthenticatedCrmSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmTasksRoute = AuthenticatedCrmTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCrmLeadsIndexRoute =
  AuthenticatedCrmLeadsIndexRouteImport.update({
    id: '/leads/',
    path: '/leads/',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmLeadsIdRoute = AuthenticatedCrmLeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const ApiPublicCronAdsRoute = ApiPublicCronAdsRouteImport.update({
  id: '/api/public/cron/ads',
  path: '/api/public/cron/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronCrmCadencesRoute =
  ApiPublicCronCrmCadencesRouteImport.update({
    id: '/api/public/cron/crm-cadences',
    path: '/api/public/cron/crm-cadences',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronCrmDailyRoute = ApiPublicCronCrmDailyRouteImport.update({
  id: '/api/public/cron/crm-daily',
  path: '/api/public/cron/crm-daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronInstagramRoute = ApiPublicCronInstagramRouteImport.update({
  id: '/api/public/cron/instagram',
  path: '/api/public/cron/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMcpCallbackRoute = ApiPublicMcpCallbackRouteImport.update({
  id: '/api/public/mcp/callback',
  path: '/api/public/mcp/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksWhatsappTokenRoute =
  ApiPublicWebhooksWhatsappTokenRouteImport.update({
    id: '/api/public/webhooks/whatsapp/$token',
    path: '/api/public/webhooks/whatsapp/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksMetaLeadgenTokenRoute =
  ApiPublicWebhooksMetaLeadgenTokenRouteImport.update({
    id: '/api/public/webhooks/meta/leadgen/$token',
    path: '/api/public/webhooks/meta/leadgen/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/crm': typeof AuthenticatedCrmRouteWithChildren
  '/insights': typeof AuthenticatedInsightsRoute
  '/instagram': typeof AuthenticatedInstagramRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/brands/$id': typeof AuthenticatedBrandsIdRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/crm/cadences': typeof AuthenticatedCrmCadencesRoute
  '/crm/dashboard': typeof AuthenticatedCrmDashboardRoute
  '/crm/inbox': typeof AuthenticatedCrmInboxRoute
  '/crm/integrations': typeof AuthenticatedCrmIntegrationsRoute
  '/crm/settings': typeof AuthenticatedCrmSettingsRoute
  '/crm/tasks': typeof AuthenticatedCrmTasksRoute
  '/brands/': typeof AuthenticatedBrandsIndexRoute
  '/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
  '/crm/leads/$id': typeof AuthenticatedCrmLeadsIdRoute
  '/api/public/cron/ads': typeof ApiPublicCronAdsRoute
  '/api/public/cron/crm-cadences': typeof ApiPublicCronCrmCadencesRoute
  '/api/public/cron/crm-daily': typeof ApiPublicCronCrmDailyRoute
  '/api/public/cron/instagram': typeof ApiPublicCronInstagramRoute
  '/api/public/mcp/callback': typeof ApiPublicMcpCallbackRoute
  '/crm/leads/': typeof AuthenticatedCrmLeadsIndexRoute
  '/api/public/webhooks/whatsapp/$token': typeof ApiPublicWebhooksWhatsappTokenRoute
  '/api/public/webhooks/meta/leadgen/$token': typeof ApiPublicWebhooksMetaLeadgenTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/instagram': typeof AuthenticatedInstagramRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/brands/$id': typeof AuthenticatedBrandsIdRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/crm/cadences': typeof AuthenticatedCrmCadencesRoute
  '/crm/dashboard': typeof AuthenticatedCrmDashboardRoute
  '/crm/inbox': typeof AuthenticatedCrmInboxRoute
  '/crm/integrations': typeof AuthenticatedCrmIntegrationsRoute
  '/crm/settings': typeof AuthenticatedCrmSettingsRoute
  '/crm/tasks': typeof AuthenticatedCrmTasksRoute
  '/brands': typeof AuthenticatedBrandsIndexRoute
  '/campaigns': typeof AuthenticatedCampaignsIndexRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
  '/crm/leads/$id': typeof AuthenticatedCrmLeadsIdRoute
  '/api/public/cron/ads': typeof ApiPublicCronAdsRoute
  '/api/public/cron/crm-cadences': typeof ApiPublicCronCrmCadencesRoute
  '/api/public/cron/crm-daily': typeof ApiPublicCronCrmDailyRoute
  '/api/public/cron/instagram': typeof ApiPublicCronInstagramRoute
  '/api/public/mcp/callback': typeof ApiPublicMcpCallbackRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsIndexRoute
  '/api/public/webhooks/whatsapp/$token': typeof ApiPublicWebhooksWhatsappTokenRoute
  '/api/public/webhooks/meta/leadgen/$token': typeof ApiPublicWebhooksMetaLeadgenTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRouteWithChildren
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/instagram': typeof AuthenticatedInstagramRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/brands/$id': typeof AuthenticatedBrandsIdRoute
  '/_authenticated/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/_authenticated/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/_authenticated/crm/cadences': typeof AuthenticatedCrmCadencesRoute
  '/_authenticated/crm/dashboard': typeof AuthenticatedCrmDashboardRoute
  '/_authenticated/crm/inbox': typeof AuthenticatedCrmInboxRoute
  '/_authenticated/crm/integrations': typeof AuthenticatedCrmIntegrationsRoute
  '/_authenticated/crm/settings': typeof AuthenticatedCrmSettingsRoute
  '/_authenticated/crm/tasks': typeof AuthenticatedCrmTasksRoute
  '/_authenticated/brands/': typeof AuthenticatedBrandsIndexRoute
  '/_authenticated/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
  '/_authenticated/crm/leads/$id': typeof AuthenticatedCrmLeadsIdRoute
  '/api/public/cron/ads': typeof ApiPublicCronAdsRoute
  '/api/public/cron/crm-cadences': typeof ApiPublicCronCrmCadencesRoute
  '/api/public/cron/crm-daily': typeof ApiPublicCronCrmDailyRoute
  '/api/public/cron/instagram': typeof ApiPublicCronInstagramRoute
  '/api/public/mcp/callback': typeof ApiPublicMcpCallbackRoute
  '/_authenticated/crm/leads/': typeof AuthenticatedCrmLeadsIndexRoute
  '/api/public/webhooks/whatsapp/$token': typeof ApiPublicWebhooksWhatsappTokenRoute
  '/api/public/webhooks/meta/leadgen/$token': typeof ApiPublicWebhooksMetaLeadgenTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/approvals'
    | '/calendar'
    | '/crm'
    | '/insights'
    | '/instagram'
    | '/integrations'
    | '/library'
    | '/overview'
    | '/performance'
    | '/settings'
    | '/studio'
    | '/brands/$id'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/crm/cadences'
    | '/crm/dashboard'
    | '/crm/inbox'
    | '/crm/integrations'
    | '/crm/settings'
    | '/crm/tasks'
    | '/brands/'
    | '/campaigns/'
    | '/crm/'
    | '/crm/leads/$id'
    | '/api/public/cron/ads'
    | '/api/public/cron/crm-cadences'
    | '/api/public/cron/crm-daily'
    | '/api/public/cron/instagram'
    | '/api/public/mcp/callback'
    | '/crm/leads/'
    | '/api/public/webhooks/whatsapp/$token'
    | '/api/public/webhooks/meta/leadgen/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/approvals'
    | '/calendar'
    | '/insights'
    | '/instagram'
    | '/integrations'
    | '/library'
    | '/overview'
    | '/performance'
    | '/settings'
    | '/studio'
    | '/brands/$id'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/crm/cadences'
    | '/crm/dashboard'
    | '/crm/inbox'
    | '/crm/integrations'
    | '/crm/settings'
    | '/crm/tasks'
    | '/brands'
    | '/campaigns'
    | '/crm'
    | '/crm/leads/$id'
    | '/api/public/cron/ads'
    | '/api/public/cron/crm-cadences'
    | '/api/public/cron/crm-daily'
    | '/api/public/cron/instagram'
    | '/api/public/mcp/callback'
    | '/crm/leads'
    | '/api/public/webhooks/whatsapp/$token'
    | '/api/public/webhooks/meta/leadgen/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/approvals'
    | '/_authenticated/calendar'
    | '/_authenticated/crm'
    | '/_authenticated/insights'
    | '/_authenticated/instagram'
    | '/_authenticated/integrations'
    | '/_authenticated/library'
    | '/_authenticated/overview'
    | '/_authenticated/performance'
    | '/_authenticated/settings'
    | '/_authenticated/studio'
    | '/_authenticated/brands/$id'
    | '/_authenticated/campaigns/$id'
    | '/_authenticated/campaigns/new'
    | '/_authenticated/crm/cadences'
    | '/_authenticated/crm/dashboard'
    | '/_authenticated/crm/inbox'
    | '/_authenticated/crm/integrations'
    | '/_authenticated/crm/settings'
    | '/_authenticated/crm/tasks'
    | '/_authenticated/brands/'
    | '/_authenticated/campaigns/'
    | '/_authenticated/crm/'
    | '/_authenticated/crm/leads/$id'
    | '/api/public/cron/ads'
    | '/api/public/cron/crm-cadences'
    | '/api/public/cron/crm-daily'
    | '/api/public/cron/instagram'
    | '/api/public/mcp/callback'
    | '/_authenticated/crm/leads/'
    | '/api/public/webhooks/whatsapp/$token'
    | '/api/public/webhooks/meta/leadgen/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCronAdsRoute: typeof ApiPublicCronAdsRoute
  ApiPublicCronCrmCadencesRoute: typeof ApiPublicCronCrmCadencesRoute
  ApiPublicCronCrmDailyRoute: typeof ApiPublicCronCrmDailyRoute
  ApiPublicCronInstagramRoute: typeof ApiPublicCronInstagramRoute
  ApiPublicMcpCallbackRoute: typeof ApiPublicMcpCallbackRoute
  ApiPublicWebhooksWhatsappTokenRoute: typeof ApiPublicWebhooksWhatsappTokenRoute
  ApiPublicWebhooksMetaLeadgenTokenRoute: typeof ApiPublicWebhooksMetaLeadgenTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instagram': {
      id: '/_authenticated/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof AuthenticatedInstagramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands/': {
      id: '/_authenticated/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof AuthenticatedBrandsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands/$id': {
      id: '/_authenticated/brands/$id'
      path: '/brands/$id'
      fullPath: '/brands/$id'
      preLoaderRoute: typeof AuthenticatedBrandsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/': {
      id: '/_authenticated/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthenticatedCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/$id': {
      id: '/_authenticated/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AuthenticatedCampaignsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/new': {
      id: '/_authenticated/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AuthenticatedCampaignsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/cadences': {
      id: '/_authenticated/crm/cadences'
      path: '/cadences'
      fullPath: '/crm/cadences'
      preLoaderRoute: typeof AuthenticatedCrmCadencesRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/dashboard': {
      id: '/_authenticated/crm/dashboard'
      path: '/dashboard'
      fullPath: '/crm/dashboard'
      preLoaderRoute: typeof AuthenticatedCrmDashboardRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/inbox': {
      id: '/_authenticated/crm/inbox'
      path: '/inbox'
      fullPath: '/crm/inbox'
      preLoaderRoute: typeof AuthenticatedCrmInboxRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/integrations': {
      id: '/_authenticated/crm/integrations'
      path: '/integrations'
      fullPath: '/crm/integrations'
      preLoaderRoute: typeof AuthenticatedCrmIntegrationsRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/settings': {
      id: '/_authenticated/crm/settings'
      path: '/settings'
      fullPath: '/crm/settings'
      preLoaderRoute: typeof AuthenticatedCrmSettingsRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/tasks': {
      id: '/_authenticated/crm/tasks'
      path: '/tasks'
      fullPath: '/crm/tasks'
      preLoaderRoute: typeof AuthenticatedCrmTasksRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/leads/': {
      id: '/_authenticated/crm/leads/'
      path: '/leads'
      fullPath: '/crm/leads/'
      preLoaderRoute: typeof AuthenticatedCrmLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/leads/$id': {
      id: '/_authenticated/crm/leads/$id'
      path: '/leads/$id'
      fullPath: '/crm/leads/$id'
      preLoaderRoute: typeof AuthenticatedCrmLeadsIdRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/api/public/cron/ads': {
      id: '/api/public/cron/ads'
      path: '/api/public/cron/ads'
      fullPath: '/api/public/cron/ads'
      preLoaderRoute: typeof ApiPublicCronAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/crm-cadences': {
      id: '/api/public/cron/crm-cadences'
      path: '/api/public/cron/crm-cadences'
      fullPath: '/api/public/cron/crm-cadences'
      preLoaderRoute: typeof ApiPublicCronCrmCadencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/crm-daily': {
      id: '/api/public/cron/crm-daily'
      path: '/api/public/cron/crm-daily'
      fullPath: '/api/public/cron/crm-daily'
      preLoaderRoute: typeof ApiPublicCronCrmDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/instagram': {
      id: '/api/public/cron/instagram'
      path: '/api/public/cron/instagram'
      fullPath: '/api/public/cron/instagram'
      preLoaderRoute: typeof ApiPublicCronInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp/callback': {
      id: '/api/public/mcp/callback'
      path: '/api/public/mcp/callback'
      fullPath: '/api/public/mcp/callback'
      preLoaderRoute: typeof ApiPublicMcpCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/whatsapp/$token': {
      id: '/api/public/webhooks/whatsapp/$token'
      path: '/api/public/webhooks/whatsapp/$token'
      fullPath: '/api/public/webhooks/whatsapp/$token'
      preLoaderRoute: typeof ApiPublicWebhooksWhatsappTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/meta/leadgen/$token': {
      id: '/api/public/webhooks/meta/leadgen/$token'
      path: '/api/public/webhooks/meta/leadgen/$token'
      fullPath: '/api/public/webhooks/meta/leadgen/$token'
      preLoaderRoute: typeof ApiPublicWebhooksMetaLeadgenTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCrmRouteChildren {
  AuthenticatedCrmCadencesRoute: typeof AuthenticatedCrmCadencesRoute
  AuthenticatedCrmDashboardRoute: typeof AuthenticatedCrmDashboardRoute
  AuthenticatedCrmInboxRoute: typeof AuthenticatedCrmInboxRoute
  AuthenticatedCrmIntegrationsRoute: typeof AuthenticatedCrmIntegrationsRoute
  AuthenticatedCrmSettingsRoute: typeof AuthenticatedCrmSettingsRoute
  AuthenticatedCrmTasksRoute: typeof AuthenticatedCrmTasksRoute
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
  AuthenticatedCrmLeadsIdRoute: typeof AuthenticatedCrmLeadsIdRoute
  AuthenticatedCrmLeadsIndexRoute: typeof AuthenticatedCrmLeadsIndexRoute
}

const AuthenticatedCrmRouteChildren: AuthenticatedCrmRouteChildren = {
  AuthenticatedCrmCadencesRoute: AuthenticatedCrmCadencesRoute,
  AuthenticatedCrmDashboardRoute: AuthenticatedCrmDashboardRoute,
  AuthenticatedCrmInboxRoute: AuthenticatedCrmInboxRoute,
  AuthenticatedCrmIntegrationsRoute: AuthenticatedCrmIntegrationsRoute,
  AuthenticatedCrmSettingsRoute: AuthenticatedCrmSettingsRoute,
  AuthenticatedCrmTasksRoute: AuthenticatedCrmTasksRoute,
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
  AuthenticatedCrmLeadsIdRoute: AuthenticatedCrmLeadsIdRoute,
  AuthenticatedCrmLeadsIndexRoute: AuthenticatedCrmLeadsIndexRoute,
}

const AuthenticatedCrmRouteWithChildren =
  AuthenticatedCrmRoute._addFileChildren(AuthenticatedCrmRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRouteWithChildren
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedInstagramRoute: typeof AuthenticatedInstagramRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedBrandsIdRoute: typeof AuthenticatedBrandsIdRoute
  AuthenticatedCampaignsIdRoute: typeof AuthenticatedCampaignsIdRoute
  AuthenticatedCampaignsNewRoute: typeof AuthenticatedCampaignsNewRoute
  AuthenticatedBrandsIndexRoute: typeof AuthenticatedBrandsIndexRoute
  AuthenticatedCampaignsIndexRoute: typeof AuthenticatedCampaignsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRouteWithChildren,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedInstagramRoute: AuthenticatedInstagramRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedBrandsIdRoute: AuthenticatedBrandsIdRoute,
  AuthenticatedCampaignsIdRoute: AuthenticatedCampaignsIdRoute,
  AuthenticatedCampaignsNewRoute: AuthenticatedCampaignsNewRoute,
  AuthenticatedBrandsIndexRoute: AuthenticatedBrandsIndexRoute,
  AuthenticatedCampaignsIndexRoute: AuthenticatedCampaignsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCronAdsRoute: ApiPublicCronAdsRoute,
  ApiPublicCronCrmCadencesRoute: ApiPublicCronCrmCadencesRoute,
  ApiPublicCronCrmDailyRoute: ApiPublicCronCrmDailyRoute,
  ApiPublicCronInstagramRoute: ApiPublicCronInstagramRoute,
  ApiPublicMcpCallbackRoute: ApiPublicMcpCallbackRoute,
  ApiPublicWebhooksWhatsappTokenRoute: ApiPublicWebhooksWhatsappTokenRoute,
  ApiPublicWebhooksMetaLeadgenTokenRoute:
    ApiPublicWebhooksMetaLeadgenTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
