-- lovable-cron-fallback-reviewed: user explicitly requested existing 5-min jobs moved to custom domain; queue/media/metrics are time-based polling of external providers
do $$ begin
  perform cron.unschedule(j) from unnest(array['crm-cadences-5min','instagram-autopilot-weekly','instagram-optimizer-monday','instagram-queue-5min','instagram-media-5min','instagram-metrics-5min']) j where exists (select 1 from cron.job where jobname=j);
end $$;

select cron.schedule('crm-cadences-5min','*/5 * * * *',$c$select net.http_post(url := 'https://www.meufunildevendas.com.br/api/public/cron/crm-cadences', headers := jsonb_build_object('Content-Type','application/json','x-cron-secret',(select token from public.cron_tokens where name='crm_cadences')), body := '{}'::jsonb);$c$);
select cron.schedule('instagram-queue-5min','*/5 * * * *',$c$select net.http_post(url := 'https://www.meufunildevendas.com.br/api/public/cron/instagram', headers := jsonb_build_object('Content-Type','application/json','x-cron-secret',(select token from public.cron_tokens where name='instagram')), body := '{"task":"queue"}'::jsonb);$c$);
select cron.schedule('instagram-media-5min','*/5 * * * *',$c$select net.http_post(url := 'https://www.meufunildevendas.com.br/api/public/cron/instagram', headers := jsonb_build_object('Content-Type','application/json','x-cron-secret',(select token from public.cron_tokens where name='instagram')), body := '{"task":"media"}'::jsonb);$c$);
select cron.schedule('instagram-metrics-5min','*/5 * * * *',$c$select net.http_post(url := 'https://www.meufunildevendas.com.br/api/public/cron/instagram', headers := jsonb_build_object('Content-Type','application/json','x-cron-secret',(select token from public.cron_tokens where name='instagram')), body := '{"task":"metrics"}'::jsonb);$c$);
select cron.schedule('instagram-autopilot-weekly','0 21 * * 0',$c$select net.http_post(url := 'https://www.meufunildevendas.com.br/api/public/cron/instagram', headers := jsonb_build_object('Content-Type','application/json','x-cron-secret',(select token from public.cron_tokens where name='instagram')), body := '{"task":"weekly"}'::jsonb);$c$);
select cron.schedule('instagram-optimizer-monday','0 12 * * 1',$c$select net.http_post(url := 'https://www.meufunildevendas.com.br/api/public/cron/instagram', headers := jsonb_build_object('Content-Type','application/json','x-cron-secret',(select token from public.cron_tokens where name='instagram')), body := '{"task":"optimize"}'::jsonb);$c$);